version: '3.8'

services:
  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ROOTNAME
      MINIO_ROOT_PASSWORD: CHANGEME123
    volumes:
      - ~/minio/data:/data
    command: server /data --console-address ":9001"

  redis:
    image: redis:latest

    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    restart: always
